package org.nescent.evogen.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * Biodatabase generated by MyEclipse - Hibernate Tools
 */

public class Biodatabase  implements java.io.Serializable {


    // Fields    

     private Integer biodatabaseId;
     private String name;
     private String authority;
     private String description;
     private Set trees = new HashSet(0);
     private Set bioentries = new HashSet(0);


    // Constructors

    /** default constructor */
    public Biodatabase() {
    }

	/** minimal constructor */
    public Biodatabase(String name) {
        this.name = name;
    }
    
    /** full constructor */
    public Biodatabase(String name, String authority, String description, Set trees, Set bioentries) {
        this.name = name;
        this.authority = authority;
        this.description = description;
        this.trees = trees;
        this.bioentries = bioentries;
    }

   
    // Property accessors

    public Integer getBiodatabaseId() {
        return this.biodatabaseId;
    }
    
    public void setBiodatabaseId(Integer biodatabaseId) {
        this.biodatabaseId = biodatabaseId;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getAuthority() {
        return this.authority;
    }
    
    public void setAuthority(String authority) {
        this.authority = authority;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public Set getTrees() {
        return this.trees;
    }
    
    public void setTrees(Set trees) {
        this.trees = trees;
    }

    public Set getBioentries() {
        return this.bioentries;
    }
    
    public void setBioentries(Set bioentries) {
        this.bioentries = bioentries;
    }
   








}