package org.nescent.evogen.hibernate;



/**
 * BioentryQualifierValue generated by MyEclipse - Hibernate Tools
 */

public class BioentryQualifierValue  implements java.io.Serializable {


    // Fields    

     private BioentryQualifierValueId id;
     private Term term;
     private Bioentry bioentry;


    // Constructors

    /** default constructor */
    public BioentryQualifierValue() {
    }

    
    /** full constructor */
    public BioentryQualifierValue(Term term, Bioentry bioentry) {
        this.term = term;
        this.bioentry = bioentry;
    }

   
    // Property accessors

    public BioentryQualifierValueId getId() {
        return this.id;
    }
    
    public void setId(BioentryQualifierValueId id) {
        this.id = id;
    }

    public Term getTerm() {
        return this.term;
    }
    
    public void setTerm(Term term) {
        this.term = term;
    }

    public Bioentry getBioentry() {
        return this.bioentry;
    }
    
    public void setBioentry(Bioentry bioentry) {
        this.bioentry = bioentry;
    }
   








}