package org.nescent.evogen.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * Bioentry generated by MyEclipse - Hibernate Tools
 */

public class Bioentry  implements java.io.Serializable {


    // Fields    

     private Integer bioentryId;
     private Biodatabase biodatabase;
     private Taxon taxon;
     private String name;
     private String accession;
     private String identifier;
     private String division;
     private String description;
     private Integer version;
     private Set bioentryPathsForObjectBioentryId = new HashSet(0);
     private Set bioentryReferences = new HashSet(0);
     private Set bioentryRelationshipsForObjectBioentryId = new HashSet(0);
     private Set comments = new HashSet(0);
     private Set bioentryPathsForSubjectBioentryId = new HashSet(0);
     private Set bioentryQualifierValues = new HashSet(0);
     private Set bioentryRelationshipsForSubjectBioentryId = new HashSet(0);
     private Set bioentryDbxrefs = new HashSet(0);
     private Set seqfeatures = new HashSet(0);
     private Set nodes = new HashSet(0);
     private Set biosequences = new HashSet(0);


    // Constructors

    /** default constructor */
    public Bioentry() {
    }

	/** minimal constructor */
    public Bioentry(Biodatabase biodatabase, String name, String accession, Integer version) {
        this.biodatabase = biodatabase;
        this.name = name;
        this.accession = accession;
        this.version = version;
    }
    
    /** full constructor */
    public Bioentry(Biodatabase biodatabase, Taxon taxon, String name, String accession, String identifier, String division, String description, Integer version, Set bioentryPathsForObjectBioentryId, Set bioentryReferences, Set bioentryRelationshipsForObjectBioentryId, Set comments, Set bioentryPathsForSubjectBioentryId, Set bioentryQualifierValues, Set bioentryRelationshipsForSubjectBioentryId, Set bioentryDbxrefs, Set seqfeatures, Set nodes, Set biosequences) {
        this.biodatabase = biodatabase;
        this.taxon = taxon;
        this.name = name;
        this.accession = accession;
        this.identifier = identifier;
        this.division = division;
        this.description = description;
        this.version = version;
        this.bioentryPathsForObjectBioentryId = bioentryPathsForObjectBioentryId;
        this.bioentryReferences = bioentryReferences;
        this.bioentryRelationshipsForObjectBioentryId = bioentryRelationshipsForObjectBioentryId;
        this.comments = comments;
        this.bioentryPathsForSubjectBioentryId = bioentryPathsForSubjectBioentryId;
        this.bioentryQualifierValues = bioentryQualifierValues;
        this.bioentryRelationshipsForSubjectBioentryId = bioentryRelationshipsForSubjectBioentryId;
        this.bioentryDbxrefs = bioentryDbxrefs;
        this.seqfeatures = seqfeatures;
        this.nodes = nodes;
        this.biosequences = biosequences;
    }

   
    // Property accessors

    public Integer getBioentryId() {
        return this.bioentryId;
    }
    
    public void setBioentryId(Integer bioentryId) {
        this.bioentryId = bioentryId;
    }

    public Biodatabase getBiodatabase() {
        return this.biodatabase;
    }
    
    public void setBiodatabase(Biodatabase biodatabase) {
        this.biodatabase = biodatabase;
    }

    public Taxon getTaxon() {
        return this.taxon;
    }
    
    public void setTaxon(Taxon taxon) {
        this.taxon = taxon;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getAccession() {
        return this.accession;
    }
    
    public void setAccession(String accession) {
        this.accession = accession;
    }

    public String getIdentifier() {
        return this.identifier;
    }
    
    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    public String getDivision() {
        return this.division;
    }
    
    public void setDivision(String division) {
        this.division = division;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public Set getBioentryPathsForObjectBioentryId() {
        return this.bioentryPathsForObjectBioentryId;
    }
    
    public void setBioentryPathsForObjectBioentryId(Set bioentryPathsForObjectBioentryId) {
        this.bioentryPathsForObjectBioentryId = bioentryPathsForObjectBioentryId;
    }

    public Set getBioentryReferences() {
        return this.bioentryReferences;
    }
    
    public void setBioentryReferences(Set bioentryReferences) {
        this.bioentryReferences = bioentryReferences;
    }

    public Set getBioentryRelationshipsForObjectBioentryId() {
        return this.bioentryRelationshipsForObjectBioentryId;
    }
    
    public void setBioentryRelationshipsForObjectBioentryId(Set bioentryRelationshipsForObjectBioentryId) {
        this.bioentryRelationshipsForObjectBioentryId = bioentryRelationshipsForObjectBioentryId;
    }

    public Set getComments() {
        return this.comments;
    }
    
    public void setComments(Set comments) {
        this.comments = comments;
    }

    public Set getBioentryPathsForSubjectBioentryId() {
        return this.bioentryPathsForSubjectBioentryId;
    }
    
    public void setBioentryPathsForSubjectBioentryId(Set bioentryPathsForSubjectBioentryId) {
        this.bioentryPathsForSubjectBioentryId = bioentryPathsForSubjectBioentryId;
    }

    public Set getBioentryQualifierValues() {
        return this.bioentryQualifierValues;
    }
    
    public void setBioentryQualifierValues(Set bioentryQualifierValues) {
        this.bioentryQualifierValues = bioentryQualifierValues;
    }

    public Set getBioentryRelationshipsForSubjectBioentryId() {
        return this.bioentryRelationshipsForSubjectBioentryId;
    }
    
    public void setBioentryRelationshipsForSubjectBioentryId(Set bioentryRelationshipsForSubjectBioentryId) {
        this.bioentryRelationshipsForSubjectBioentryId = bioentryRelationshipsForSubjectBioentryId;
    }

    public Set getBioentryDbxrefs() {
        return this.bioentryDbxrefs;
    }
    
    public void setBioentryDbxrefs(Set bioentryDbxrefs) {
        this.bioentryDbxrefs = bioentryDbxrefs;
    }

    public Set getSeqfeatures() {
        return this.seqfeatures;
    }
    
    public void setSeqfeatures(Set seqfeatures) {
        this.seqfeatures = seqfeatures;
    }

    public Set getNodes() {
        return this.nodes;
    }
    
    public void setNodes(Set nodes) {
        this.nodes = nodes;
    }

    public Set getBiosequences() {
        return this.biosequences;
    }
    
    public void setBiosequences(Set biosequences) {
        this.biosequences = biosequences;
    }
   








}