package org.nescent.evogen.hibernate;



/**
 * BioentryReferenceId generated by MyEclipse - Hibernate Tools
 */

public class BioentryReferenceId  implements java.io.Serializable {


    // Fields    

     private Bioentry bioentry;
     private Reference reference;
     private Integer rank;


    // Constructors

    /** default constructor */
    public BioentryReferenceId() {
    }

    
    /** full constructor */
    public BioentryReferenceId(Bioentry bioentry, Reference reference, Integer rank) {
        this.bioentry = bioentry;
        this.reference = reference;
        this.rank = rank;
    }

   
    // Property accessors

    public Bioentry getBioentry() {
        return this.bioentry;
    }
    
    public void setBioentry(Bioentry bioentry) {
        this.bioentry = bioentry;
    }

    public Reference getReference() {
        return this.reference;
    }
    
    public void setReference(Reference reference) {
        this.reference = reference;
    }

    public Integer getRank() {
        return this.rank;
    }
    
    public void setRank(Integer rank) {
        this.rank = rank;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BioentryReferenceId) ) return false;
		 BioentryReferenceId castOther = ( BioentryReferenceId ) other; 
         
		 return ( (this.getBioentry()==castOther.getBioentry()) || ( this.getBioentry()!=null && castOther.getBioentry()!=null && this.getBioentry().equals(castOther.getBioentry()) ) )
 && ( (this.getReference()==castOther.getReference()) || ( this.getReference()!=null && castOther.getReference()!=null && this.getReference().equals(castOther.getReference()) ) )
 && ( (this.getRank()==castOther.getRank()) || ( this.getRank()!=null && castOther.getRank()!=null && this.getRank().equals(castOther.getRank()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getBioentry() == null ? 0 : this.getBioentry().hashCode() );
         result = 37 * result + ( getReference() == null ? 0 : this.getReference().hashCode() );
         result = 37 * result + ( getRank() == null ? 0 : this.getRank().hashCode() );
         return result;
   }   





}