package org.nescent.evogen.hibernate;



/**
 * BioentryPath generated by MyEclipse - Hibernate Tools
 */

public class BioentryPath  implements java.io.Serializable {


    // Fields    

     private BioentryPathId id;
     private Term term;
     private Bioentry bioentryByObjectBioentryId;
     private Bioentry bioentryBySubjectBioentryId;


    // Constructors

    /** default constructor */
    public BioentryPath() {
    }

    
    /** full constructor */
    public BioentryPath(Term term, Bioentry bioentryByObjectBioentryId, Bioentry bioentryBySubjectBioentryId) {
        this.term = term;
        this.bioentryByObjectBioentryId = bioentryByObjectBioentryId;
        this.bioentryBySubjectBioentryId = bioentryBySubjectBioentryId;
    }

   
    // Property accessors

    public BioentryPathId getId() {
        return this.id;
    }
    
    public void setId(BioentryPathId id) {
        this.id = id;
    }

    public Term getTerm() {
        return this.term;
    }
    
    public void setTerm(Term term) {
        this.term = term;
    }

    public Bioentry getBioentryByObjectBioentryId() {
        return this.bioentryByObjectBioentryId;
    }
    
    public void setBioentryByObjectBioentryId(Bioentry bioentryByObjectBioentryId) {
        this.bioentryByObjectBioentryId = bioentryByObjectBioentryId;
    }

    public Bioentry getBioentryBySubjectBioentryId() {
        return this.bioentryBySubjectBioentryId;
    }
    
    public void setBioentryBySubjectBioentryId(Bioentry bioentryBySubjectBioentryId) {
        this.bioentryBySubjectBioentryId = bioentryBySubjectBioentryId;
    }
   








}