package org.nescent.evogen.hibernate;



/**
 * BioentryPathId generated by MyEclipse - Hibernate Tools
 */

public class BioentryPathId  implements java.io.Serializable {


    // Fields    

     private Bioentry bioentry;
     private Bioentry bioentry_1;
     private Term term;
     private Integer distance;


    // Constructors

    /** default constructor */
    public BioentryPathId() {
    }

	/** minimal constructor */
    public BioentryPathId(Bioentry bioentry, Bioentry bioentry_1, Term term) {
        this.bioentry = bioentry;
        this.bioentry_1 = bioentry_1;
        this.term = term;
    }
    
    /** full constructor */
    public BioentryPathId(Bioentry bioentry, Bioentry bioentry_1, Term term, Integer distance) {
        this.bioentry = bioentry;
        this.bioentry_1 = bioentry_1;
        this.term = term;
        this.distance = distance;
    }

   
    // Property accessors

    public Bioentry getBioentry() {
        return this.bioentry;
    }
    
    public void setBioentry(Bioentry bioentry) {
        this.bioentry = bioentry;
    }

    public Bioentry getBioentry_1() {
        return this.bioentry_1;
    }
    
    public void setBioentry_1(Bioentry bioentry_1) {
        this.bioentry_1 = bioentry_1;
    }

    public Term getTerm() {
        return this.term;
    }
    
    public void setTerm(Term term) {
        this.term = term;
    }

    public Integer getDistance() {
        return this.distance;
    }
    
    public void setDistance(Integer distance) {
        this.distance = distance;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BioentryPathId) ) return false;
		 BioentryPathId castOther = ( BioentryPathId ) other; 
         
		 return ( (this.getBioentry()==castOther.getBioentry()) || ( this.getBioentry()!=null && castOther.getBioentry()!=null && this.getBioentry().equals(castOther.getBioentry()) ) )
 && ( (this.getBioentry_1()==castOther.getBioentry_1()) || ( this.getBioentry_1()!=null && castOther.getBioentry_1()!=null && this.getBioentry_1().equals(castOther.getBioentry_1()) ) )
 && ( (this.getTerm()==castOther.getTerm()) || ( this.getTerm()!=null && castOther.getTerm()!=null && this.getTerm().equals(castOther.getTerm()) ) )
 && ( (this.getDistance()==castOther.getDistance()) || ( this.getDistance()!=null && castOther.getDistance()!=null && this.getDistance().equals(castOther.getDistance()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getBioentry() == null ? 0 : this.getBioentry().hashCode() );
         result = 37 * result + ( getBioentry_1() == null ? 0 : this.getBioentry_1().hashCode() );
         result = 37 * result + ( getTerm() == null ? 0 : this.getTerm().hashCode() );
         result = 37 * result + ( getDistance() == null ? 0 : this.getDistance().hashCode() );
         return result;
   }   





}