package org.nescent.evogen.hibernate;



/**
 * BioentryReference generated by MyEclipse - Hibernate Tools
 */

public class BioentryReference  implements java.io.Serializable {


    // Fields    

     private BioentryReferenceId id;
     private Integer startPos;
     private Integer endPos;


    // Constructors

    /** default constructor */
    public BioentryReference() {
    }

    
    /** full constructor */
    public BioentryReference(Integer startPos, Integer endPos) {
        this.startPos = startPos;
        this.endPos = endPos;
    }

   
    // Property accessors

    public BioentryReferenceId getId() {
        return this.id;
    }
    
    public void setId(BioentryReferenceId id) {
        this.id = id;
    }

    public Integer getStartPos() {
        return this.startPos;
    }
    
    public void setStartPos(Integer startPos) {
        this.startPos = startPos;
    }

    public Integer getEndPos() {
        return this.endPos;
    }
    
    public void setEndPos(Integer endPos) {
        this.endPos = endPos;
    }
   








}