package org.nescent.evogen.hibernate;



/**
 * BioentryQualifierValueId generated by MyEclipse - Hibernate Tools
 */

public class BioentryQualifierValueId  implements java.io.Serializable {


    // Fields    

     private Bioentry bioentry;
     private Term term;
     private String value;
     private Integer rank;


    // Constructors

    /** default constructor */
    public BioentryQualifierValueId() {
    }

	/** minimal constructor */
    public BioentryQualifierValueId(Bioentry bioentry, Term term, Integer rank) {
        this.bioentry = bioentry;
        this.term = term;
        this.rank = rank;
    }
    
    /** full constructor */
    public BioentryQualifierValueId(Bioentry bioentry, Term term, String value, Integer rank) {
        this.bioentry = bioentry;
        this.term = term;
        this.value = value;
        this.rank = rank;
    }

   
    // Property accessors

    public Bioentry getBioentry() {
        return this.bioentry;
    }
    
    public void setBioentry(Bioentry bioentry) {
        this.bioentry = bioentry;
    }

    public Term getTerm() {
        return this.term;
    }
    
    public void setTerm(Term term) {
        this.term = term;
    }

    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }

    public Integer getRank() {
        return this.rank;
    }
    
    public void setRank(Integer rank) {
        this.rank = rank;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BioentryQualifierValueId) ) return false;
		 BioentryQualifierValueId castOther = ( BioentryQualifierValueId ) other; 
         
		 return ( (this.getBioentry()==castOther.getBioentry()) || ( this.getBioentry()!=null && castOther.getBioentry()!=null && this.getBioentry().equals(castOther.getBioentry()) ) )
 && ( (this.getTerm()==castOther.getTerm()) || ( this.getTerm()!=null && castOther.getTerm()!=null && this.getTerm().equals(castOther.getTerm()) ) )
 && ( (this.getValue()==castOther.getValue()) || ( this.getValue()!=null && castOther.getValue()!=null && this.getValue().equals(castOther.getValue()) ) )
 && ( (this.getRank()==castOther.getRank()) || ( this.getRank()!=null && castOther.getRank()!=null && this.getRank().equals(castOther.getRank()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getBioentry() == null ? 0 : this.getBioentry().hashCode() );
         result = 37 * result + ( getTerm() == null ? 0 : this.getTerm().hashCode() );
         result = 37 * result + ( getValue() == null ? 0 : this.getValue().hashCode() );
         result = 37 * result + ( getRank() == null ? 0 : this.getRank().hashCode() );
         return result;
   }   





}