package org.nescent.evogen.hibernate;



/**
 * Biosequence generated by MyEclipse - Hibernate Tools
 */

public class Biosequence  implements java.io.Serializable {


    // Fields    

     private Integer bioentryId;
     private Bioentry bioentry;
     private Integer version;
     private Integer length;
     private String alphabet;
     private String seq;


    // Constructors

    /** default constructor */
    public Biosequence() {
    }

	/** minimal constructor */
    public Biosequence(Bioentry bioentry) {
        this.bioentry = bioentry;
    }
    
    /** full constructor */
    public Biosequence(Bioentry bioentry, Integer version, Integer length, String alphabet, String seq) {
        this.bioentry = bioentry;
        this.version = version;
        this.length = length;
        this.alphabet = alphabet;
        this.seq = seq;
    }

   
    // Property accessors

    public Integer getBioentryId() {
        return this.bioentryId;
    }
    
    public void setBioentryId(Integer bioentryId) {
        this.bioentryId = bioentryId;
    }

    public Bioentry getBioentry() {
        return this.bioentry;
    }
    
    public void setBioentry(Bioentry bioentry) {
        this.bioentry = bioentry;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public Integer getLength() {
        return this.length;
    }
    
    public void setLength(Integer length) {
        this.length = length;
    }

    public String getAlphabet() {
        return this.alphabet;
    }
    
    public void setAlphabet(String alphabet) {
        this.alphabet = alphabet;
    }

    public String getSeq() {
        return this.seq;
    }
    
    public void setSeq(String seq) {
        this.seq = seq;
    }
   








}