package org.nescent.evogen.hibernate;



/**
 * Comment generated by MyEclipse - Hibernate Tools
 */

public class Comment  implements java.io.Serializable {


    // Fields    

     private Integer commentId;
     private Bioentry bioentry;
     private String commentText;
     private Integer rank;


    // Constructors

    /** default constructor */
    public Comment() {
    }

    
    /** full constructor */
    public Comment(Bioentry bioentry, String commentText, Integer rank) {
        this.bioentry = bioentry;
        this.commentText = commentText;
        this.rank = rank;
    }

   
    // Property accessors

    public Integer getCommentId() {
        return this.commentId;
    }
    
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    public Bioentry getBioentry() {
        return this.bioentry;
    }
    
    public void setBioentry(Bioentry bioentry) {
        this.bioentry = bioentry;
    }

    public String getCommentText() {
        return this.commentText;
    }
    
    public void setCommentText(String commentText) {
        this.commentText = commentText;
    }

    public Integer getRank() {
        return this.rank;
    }
    
    public void setRank(Integer rank) {
        this.rank = rank;
    }
   








}