package org.nescent.evogen.hibernate;



/**
 * DbxrefQualifierValue generated by MyEclipse - Hibernate Tools
 */

public class DbxrefQualifierValue  implements java.io.Serializable {


    // Fields    

     private DbxrefQualifierValueId id;
     private String value;


    // Constructors

    /** default constructor */
    public DbxrefQualifierValue() {
    }

    
    /** full constructor */
    public DbxrefQualifierValue(String value) {
        this.value = value;
    }

   
    // Property accessors

    public DbxrefQualifierValueId getId() {
        return this.id;
    }
    
    public void setId(DbxrefQualifierValueId id) {
        this.id = id;
    }

    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
   








}