package org.nescent.evogen.hibernate;



/**
 * DbxrefQualifierValueId generated by MyEclipse - Hibernate Tools
 */

public class DbxrefQualifierValueId  implements java.io.Serializable {


    // Fields    

     private Dbxref dbxref;
     private Term term;
     private Integer rank;


    // Constructors

    /** default constructor */
    public DbxrefQualifierValueId() {
    }

    
    /** full constructor */
    public DbxrefQualifierValueId(Dbxref dbxref, Term term, Integer rank) {
        this.dbxref = dbxref;
        this.term = term;
        this.rank = rank;
    }

   
    // Property accessors

    public Dbxref getDbxref() {
        return this.dbxref;
    }
    
    public void setDbxref(Dbxref dbxref) {
        this.dbxref = dbxref;
    }

    public Term getTerm() {
        return this.term;
    }
    
    public void setTerm(Term term) {
        this.term = term;
    }

    public Integer getRank() {
        return this.rank;
    }
    
    public void setRank(Integer rank) {
        this.rank = rank;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DbxrefQualifierValueId) ) return false;
		 DbxrefQualifierValueId castOther = ( DbxrefQualifierValueId ) other; 
         
		 return ( (this.getDbxref()==castOther.getDbxref()) || ( this.getDbxref()!=null && castOther.getDbxref()!=null && this.getDbxref().equals(castOther.getDbxref()) ) )
 && ( (this.getTerm()==castOther.getTerm()) || ( this.getTerm()!=null && castOther.getTerm()!=null && this.getTerm().equals(castOther.getTerm()) ) )
 && ( (this.getRank()==castOther.getRank()) || ( this.getRank()!=null && castOther.getRank()!=null && this.getRank().equals(castOther.getRank()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDbxref() == null ? 0 : this.getDbxref().hashCode() );
         result = 37 * result + ( getTerm() == null ? 0 : this.getTerm().hashCode() );
         result = 37 * result + ( getRank() == null ? 0 : this.getRank().hashCode() );
         return result;
   }   





}