package org.nescent.evogen.hibernate;



/**
 * LocationQualifierValue generated by MyEclipse - Hibernate Tools
 */

public class LocationQualifierValue  implements java.io.Serializable {


    // Fields    

     private LocationQualifierValueId id;
     private String value;
     private Integer intValue;


    // Constructors

    /** default constructor */
    public LocationQualifierValue() {
    }

	/** minimal constructor */
    public LocationQualifierValue(String value) {
        this.value = value;
    }
    
    /** full constructor */
    public LocationQualifierValue(String value, Integer intValue) {
        this.value = value;
        this.intValue = intValue;
    }

   
    // Property accessors

    public LocationQualifierValueId getId() {
        return this.id;
    }
    
    public void setId(LocationQualifierValueId id) {
        this.id = id;
    }

    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }

    public Integer getIntValue() {
        return this.intValue;
    }
    
    public void setIntValue(Integer intValue) {
        this.intValue = intValue;
    }
   








}