package org.nescent.evogen.hibernate;



/**
 * NodeAttributeValueId generated by MyEclipse - Hibernate Tools
 */

public class NodeAttributeValueId  implements java.io.Serializable {


    // Fields    

     private String value;
     private Node node;
     private Term term;


    // Constructors

    /** default constructor */
    public NodeAttributeValueId() {
    }

	/** minimal constructor */
    public NodeAttributeValueId(Node node, Term term) {
        this.node = node;
        this.term = term;
    }
    
    /** full constructor */
    public NodeAttributeValueId(String value, Node node, Term term) {
        this.value = value;
        this.node = node;
        this.term = term;
    }

   
    // Property accessors

    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }

    public Node getNode() {
        return this.node;
    }
    
    public void setNode(Node node) {
        this.node = node;
    }

    public Term getTerm() {
        return this.term;
    }
    
    public void setTerm(Term term) {
        this.term = term;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof NodeAttributeValueId) ) return false;
		 NodeAttributeValueId castOther = ( NodeAttributeValueId ) other; 
         
		 return ( (this.getValue()==castOther.getValue()) || ( this.getValue()!=null && castOther.getValue()!=null && this.getValue().equals(castOther.getValue()) ) )
 && ( (this.getNode()==castOther.getNode()) || ( this.getNode()!=null && castOther.getNode()!=null && this.getNode().equals(castOther.getNode()) ) )
 && ( (this.getTerm()==castOther.getTerm()) || ( this.getTerm()!=null && castOther.getTerm()!=null && this.getTerm().equals(castOther.getTerm()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getValue() == null ? 0 : this.getValue().hashCode() );
         result = 37 * result + ( getNode() == null ? 0 : this.getNode().hashCode() );
         result = 37 * result + ( getTerm() == null ? 0 : this.getTerm().hashCode() );
         return result;
   }   





}