package org.nescent.evogen.hibernate;



/**
 * NodePath generated by MyEclipse - Hibernate Tools
 */

public class NodePath  implements java.io.Serializable {


    // Fields    

     private NodePathId id;
     private String path;


    // Constructors

    /** default constructor */
    public NodePath() {
    }

    
    /** full constructor */
    public NodePath(String path) {
        this.path = path;
    }

   
    // Property accessors

    public NodePathId getId() {
        return this.id;
    }
    
    public void setId(NodePathId id) {
        this.id = id;
    }

    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }
   








}