package org.nescent.evogen.hibernate;



/**
 * NodeAttributeValue generated by MyEclipse - Hibernate Tools
 */

public class NodeAttributeValue  implements java.io.Serializable {


    // Fields    

     private NodeAttributeValueId id;
     private Term term;
     private Node node;


    // Constructors

    /** default constructor */
    public NodeAttributeValue() {
    }

    
    /** full constructor */
    public NodeAttributeValue(Term term, Node node) {
        this.term = term;
        this.node = node;
    }

   
    // Property accessors

    public NodeAttributeValueId getId() {
        return this.id;
    }
    
    public void setId(NodeAttributeValueId id) {
        this.id = id;
    }

    public Term getTerm() {
        return this.term;
    }
    
    public void setTerm(Term term) {
        this.term = term;
    }

    public Node getNode() {
        return this.node;
    }
    
    public void setNode(Node node) {
        this.node = node;
    }
   








}