package org.nescent.evogen.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * Ontology generated by MyEclipse - Hibernate Tools
 */

public class Ontology  implements java.io.Serializable {


    // Fields    

     private Integer ontologyId;
     private String name;
     private String definition;
     private Set terms = new HashSet(0);
     private Set termPaths = new HashSet(0);
     private Set termRelationships = new HashSet(0);


    // Constructors

    /** default constructor */
    public Ontology() {
    }

	/** minimal constructor */
    public Ontology(String name) {
        this.name = name;
    }
    
    /** full constructor */
    public Ontology(String name, String definition, Set terms, Set termPaths, Set termRelationships) {
        this.name = name;
        this.definition = definition;
        this.terms = terms;
        this.termPaths = termPaths;
        this.termRelationships = termRelationships;
    }

   
    // Property accessors

    public Integer getOntologyId() {
        return this.ontologyId;
    }
    
    public void setOntologyId(Integer ontologyId) {
        this.ontologyId = ontologyId;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getDefinition() {
        return this.definition;
    }
    
    public void setDefinition(String definition) {
        this.definition = definition;
    }

    public Set getTerms() {
        return this.terms;
    }
    
    public void setTerms(Set terms) {
        this.terms = terms;
    }

    public Set getTermPaths() {
        return this.termPaths;
    }
    
    public void setTermPaths(Set termPaths) {
        this.termPaths = termPaths;
    }

    public Set getTermRelationships() {
        return this.termRelationships;
    }
    
    public void setTermRelationships(Set termRelationships) {
        this.termRelationships = termRelationships;
    }
   








}