package org.nescent.evogen.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * Reference generated by MyEclipse - Hibernate Tools
 */

public class Reference  implements java.io.Serializable {


    // Fields    

     private Integer referenceId;
     private Dbxref dbxref;
     private String location;
     private String title;
     private String authors;
     private String crc;
     private Set bioentryReferences = new HashSet(0);


    // Constructors

    /** default constructor */
    public Reference() {
    }

	/** minimal constructor */
    public Reference(String location) {
        this.location = location;
    }
    
    /** full constructor */
    public Reference(Dbxref dbxref, String location, String title, String authors, String crc, Set bioentryReferences) {
        this.dbxref = dbxref;
        this.location = location;
        this.title = title;
        this.authors = authors;
        this.crc = crc;
        this.bioentryReferences = bioentryReferences;
    }

   
    // Property accessors

    public Integer getReferenceId() {
        return this.referenceId;
    }
    
    public void setReferenceId(Integer referenceId) {
        this.referenceId = referenceId;
    }

    public Dbxref getDbxref() {
        return this.dbxref;
    }
    
    public void setDbxref(Dbxref dbxref) {
        this.dbxref = dbxref;
    }

    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }

    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    public String getAuthors() {
        return this.authors;
    }
    
    public void setAuthors(String authors) {
        this.authors = authors;
    }

    public String getCrc() {
        return this.crc;
    }
    
    public void setCrc(String crc) {
        this.crc = crc;
    }

    public Set getBioentryReferences() {
        return this.bioentryReferences;
    }
    
    public void setBioentryReferences(Set bioentryReferences) {
        this.bioentryReferences = bioentryReferences;
    }
   








}