package org.nescent.evogen.hibernate;



/**
 * SeqfeatureDbxref generated by MyEclipse - Hibernate Tools
 */

public class SeqfeatureDbxref  implements java.io.Serializable {


    // Fields    

     private SeqfeatureDbxrefId id;
     private Integer rank;


    // Constructors

    /** default constructor */
    public SeqfeatureDbxref() {
    }

    
    /** full constructor */
    public SeqfeatureDbxref(Integer rank) {
        this.rank = rank;
    }

   
    // Property accessors

    public SeqfeatureDbxrefId getId() {
        return this.id;
    }
    
    public void setId(SeqfeatureDbxrefId id) {
        this.id = id;
    }

    public Integer getRank() {
        return this.rank;
    }
    
    public void setRank(Integer rank) {
        this.rank = rank;
    }
   








}