package org.nescent.evogen.hibernate;



/**
 * SeqfeatureDbxrefId generated by MyEclipse - Hibernate Tools
 */

public class SeqfeatureDbxrefId  implements java.io.Serializable {


    // Fields    

     private Seqfeature seqfeature;
     private Dbxref dbxref;


    // Constructors

    /** default constructor */
    public SeqfeatureDbxrefId() {
    }

    
    /** full constructor */
    public SeqfeatureDbxrefId(Seqfeature seqfeature, Dbxref dbxref) {
        this.seqfeature = seqfeature;
        this.dbxref = dbxref;
    }

   
    // Property accessors

    public Seqfeature getSeqfeature() {
        return this.seqfeature;
    }
    
    public void setSeqfeature(Seqfeature seqfeature) {
        this.seqfeature = seqfeature;
    }

    public Dbxref getDbxref() {
        return this.dbxref;
    }
    
    public void setDbxref(Dbxref dbxref) {
        this.dbxref = dbxref;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SeqfeatureDbxrefId) ) return false;
		 SeqfeatureDbxrefId castOther = ( SeqfeatureDbxrefId ) other; 
         
		 return ( (this.getSeqfeature()==castOther.getSeqfeature()) || ( this.getSeqfeature()!=null && castOther.getSeqfeature()!=null && this.getSeqfeature().equals(castOther.getSeqfeature()) ) )
 && ( (this.getDbxref()==castOther.getDbxref()) || ( this.getDbxref()!=null && castOther.getDbxref()!=null && this.getDbxref().equals(castOther.getDbxref()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSeqfeature() == null ? 0 : this.getSeqfeature().hashCode() );
         result = 37 * result + ( getDbxref() == null ? 0 : this.getDbxref().hashCode() );
         return result;
   }   





}