package org.nescent.evogen.hibernate;



/**
 * SeqfeatureQualifierValue generated by MyEclipse - Hibernate Tools
 */

public class SeqfeatureQualifierValue  implements java.io.Serializable {


    // Fields    

     private SeqfeatureQualifierValueId id;
     private String value;


    // Constructors

    /** default constructor */
    public SeqfeatureQualifierValue() {
    }

    
    /** full constructor */
    public SeqfeatureQualifierValue(String value) {
        this.value = value;
    }

   
    // Property accessors

    public SeqfeatureQualifierValueId getId() {
        return this.id;
    }
    
    public void setId(SeqfeatureQualifierValueId id) {
        this.id = id;
    }

    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
   








}