package org.nescent.evogen.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * Seqfeature generated by MyEclipse - Hibernate Tools
 */

public class Seqfeature  implements java.io.Serializable {


    // Fields    

     private Integer seqfeatureId;
     private Term termBySourceTermId;
     private Bioentry bioentry;
     private Term termByTypeTermId;
     private String displayName;
     private Integer rank;
     private Set seqfeatureRelationshipsForSubjectSeqfeatureId = new HashSet(0);
     private Set seqfeatureQualifierValues = new HashSet(0);
     private Set seqfeaturePathsForSubjectSeqfeatureId = new HashSet(0);
     private Set seqfeatureRelationshipsForObjectSeqfeatureId = new HashSet(0);
     private Set locations = new HashSet(0);
     private Set seqfeatureDbxrefs = new HashSet(0);
     private Set seqfeaturePathsForObjectSeqfeatureId = new HashSet(0);


    // Constructors

    /** default constructor */
    public Seqfeature() {
    }

	/** minimal constructor */
    public Seqfeature(Term termBySourceTermId, Bioentry bioentry, Term termByTypeTermId, Integer rank) {
        this.termBySourceTermId = termBySourceTermId;
        this.bioentry = bioentry;
        this.termByTypeTermId = termByTypeTermId;
        this.rank = rank;
    }
    
    /** full constructor */
    public Seqfeature(Term termBySourceTermId, Bioentry bioentry, Term termByTypeTermId, String displayName, Integer rank, Set seqfeatureRelationshipsForSubjectSeqfeatureId, Set seqfeatureQualifierValues, Set seqfeaturePathsForSubjectSeqfeatureId, Set seqfeatureRelationshipsForObjectSeqfeatureId, Set locations, Set seqfeatureDbxrefs, Set seqfeaturePathsForObjectSeqfeatureId) {
        this.termBySourceTermId = termBySourceTermId;
        this.bioentry = bioentry;
        this.termByTypeTermId = termByTypeTermId;
        this.displayName = displayName;
        this.rank = rank;
        this.seqfeatureRelationshipsForSubjectSeqfeatureId = seqfeatureRelationshipsForSubjectSeqfeatureId;
        this.seqfeatureQualifierValues = seqfeatureQualifierValues;
        this.seqfeaturePathsForSubjectSeqfeatureId = seqfeaturePathsForSubjectSeqfeatureId;
        this.seqfeatureRelationshipsForObjectSeqfeatureId = seqfeatureRelationshipsForObjectSeqfeatureId;
        this.locations = locations;
        this.seqfeatureDbxrefs = seqfeatureDbxrefs;
        this.seqfeaturePathsForObjectSeqfeatureId = seqfeaturePathsForObjectSeqfeatureId;
    }

   
    // Property accessors

    public Integer getSeqfeatureId() {
        return this.seqfeatureId;
    }
    
    public void setSeqfeatureId(Integer seqfeatureId) {
        this.seqfeatureId = seqfeatureId;
    }

    public Term getTermBySourceTermId() {
        return this.termBySourceTermId;
    }
    
    public void setTermBySourceTermId(Term termBySourceTermId) {
        this.termBySourceTermId = termBySourceTermId;
    }

    public Bioentry getBioentry() {
        return this.bioentry;
    }
    
    public void setBioentry(Bioentry bioentry) {
        this.bioentry = bioentry;
    }

    public Term getTermByTypeTermId() {
        return this.termByTypeTermId;
    }
    
    public void setTermByTypeTermId(Term termByTypeTermId) {
        this.termByTypeTermId = termByTypeTermId;
    }

    public String getDisplayName() {
        return this.displayName;
    }
    
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public Integer getRank() {
        return this.rank;
    }
    
    public void setRank(Integer rank) {
        this.rank = rank;
    }

    public Set getSeqfeatureRelationshipsForSubjectSeqfeatureId() {
        return this.seqfeatureRelationshipsForSubjectSeqfeatureId;
    }
    
    public void setSeqfeatureRelationshipsForSubjectSeqfeatureId(Set seqfeatureRelationshipsForSubjectSeqfeatureId) {
        this.seqfeatureRelationshipsForSubjectSeqfeatureId = seqfeatureRelationshipsForSubjectSeqfeatureId;
    }

    public Set getSeqfeatureQualifierValues() {
        return this.seqfeatureQualifierValues;
    }
    
    public void setSeqfeatureQualifierValues(Set seqfeatureQualifierValues) {
        this.seqfeatureQualifierValues = seqfeatureQualifierValues;
    }

    public Set getSeqfeaturePathsForSubjectSeqfeatureId() {
        return this.seqfeaturePathsForSubjectSeqfeatureId;
    }
    
    public void setSeqfeaturePathsForSubjectSeqfeatureId(Set seqfeaturePathsForSubjectSeqfeatureId) {
        this.seqfeaturePathsForSubjectSeqfeatureId = seqfeaturePathsForSubjectSeqfeatureId;
    }

    public Set getSeqfeatureRelationshipsForObjectSeqfeatureId() {
        return this.seqfeatureRelationshipsForObjectSeqfeatureId;
    }
    
    public void setSeqfeatureRelationshipsForObjectSeqfeatureId(Set seqfeatureRelationshipsForObjectSeqfeatureId) {
        this.seqfeatureRelationshipsForObjectSeqfeatureId = seqfeatureRelationshipsForObjectSeqfeatureId;
    }

    public Set getLocations() {
        return this.locations;
    }
    
    public void setLocations(Set locations) {
        this.locations = locations;
    }

    public Set getSeqfeatureDbxrefs() {
        return this.seqfeatureDbxrefs;
    }
    
    public void setSeqfeatureDbxrefs(Set seqfeatureDbxrefs) {
        this.seqfeatureDbxrefs = seqfeatureDbxrefs;
    }

    public Set getSeqfeaturePathsForObjectSeqfeatureId() {
        return this.seqfeaturePathsForObjectSeqfeatureId;
    }
    
    public void setSeqfeaturePathsForObjectSeqfeatureId(Set seqfeaturePathsForObjectSeqfeatureId) {
        this.seqfeaturePathsForObjectSeqfeatureId = seqfeaturePathsForObjectSeqfeatureId;
    }
   








}