package org.nescent.evogen.hibernate;



/**
 * SeqfeatureRelationship generated by MyEclipse - Hibernate Tools
 */

public class SeqfeatureRelationship  implements java.io.Serializable {


    // Fields    

     private Integer seqfeatureRelationshipId;
     private Term term;
     private Seqfeature seqfeatureByObjectSeqfeatureId;
     private Seqfeature seqfeatureBySubjectSeqfeatureId;
     private Integer rank;


    // Constructors

    /** default constructor */
    public SeqfeatureRelationship() {
    }

	/** minimal constructor */
    public SeqfeatureRelationship(Term term, Seqfeature seqfeatureByObjectSeqfeatureId, Seqfeature seqfeatureBySubjectSeqfeatureId) {
        this.term = term;
        this.seqfeatureByObjectSeqfeatureId = seqfeatureByObjectSeqfeatureId;
        this.seqfeatureBySubjectSeqfeatureId = seqfeatureBySubjectSeqfeatureId;
    }
    
    /** full constructor */
    public SeqfeatureRelationship(Term term, Seqfeature seqfeatureByObjectSeqfeatureId, Seqfeature seqfeatureBySubjectSeqfeatureId, Integer rank) {
        this.term = term;
        this.seqfeatureByObjectSeqfeatureId = seqfeatureByObjectSeqfeatureId;
        this.seqfeatureBySubjectSeqfeatureId = seqfeatureBySubjectSeqfeatureId;
        this.rank = rank;
    }

   
    // Property accessors

    public Integer getSeqfeatureRelationshipId() {
        return this.seqfeatureRelationshipId;
    }
    
    public void setSeqfeatureRelationshipId(Integer seqfeatureRelationshipId) {
        this.seqfeatureRelationshipId = seqfeatureRelationshipId;
    }

    public Term getTerm() {
        return this.term;
    }
    
    public void setTerm(Term term) {
        this.term = term;
    }

    public Seqfeature getSeqfeatureByObjectSeqfeatureId() {
        return this.seqfeatureByObjectSeqfeatureId;
    }
    
    public void setSeqfeatureByObjectSeqfeatureId(Seqfeature seqfeatureByObjectSeqfeatureId) {
        this.seqfeatureByObjectSeqfeatureId = seqfeatureByObjectSeqfeatureId;
    }

    public Seqfeature getSeqfeatureBySubjectSeqfeatureId() {
        return this.seqfeatureBySubjectSeqfeatureId;
    }
    
    public void setSeqfeatureBySubjectSeqfeatureId(Seqfeature seqfeatureBySubjectSeqfeatureId) {
        this.seqfeatureBySubjectSeqfeatureId = seqfeatureBySubjectSeqfeatureId;
    }

    public Integer getRank() {
        return this.rank;
    }
    
    public void setRank(Integer rank) {
        this.rank = rank;
    }
   








}