package org.nescent.evogen.hibernate;



/**
 * SeqfeaturePathId generated by MyEclipse - Hibernate Tools
 */

public class SeqfeaturePathId  implements java.io.Serializable {


    // Fields    

     private Seqfeature seqfeature;
     private Seqfeature seqfeature_1;
     private Term term;
     private Integer distance;


    // Constructors

    /** default constructor */
    public SeqfeaturePathId() {
    }

	/** minimal constructor */
    public SeqfeaturePathId(Seqfeature seqfeature, Seqfeature seqfeature_1, Term term) {
        this.seqfeature = seqfeature;
        this.seqfeature_1 = seqfeature_1;
        this.term = term;
    }
    
    /** full constructor */
    public SeqfeaturePathId(Seqfeature seqfeature, Seqfeature seqfeature_1, Term term, Integer distance) {
        this.seqfeature = seqfeature;
        this.seqfeature_1 = seqfeature_1;
        this.term = term;
        this.distance = distance;
    }

   
    // Property accessors

    public Seqfeature getSeqfeature() {
        return this.seqfeature;
    }
    
    public void setSeqfeature(Seqfeature seqfeature) {
        this.seqfeature = seqfeature;
    }

    public Seqfeature getSeqfeature_1() {
        return this.seqfeature_1;
    }
    
    public void setSeqfeature_1(Seqfeature seqfeature_1) {
        this.seqfeature_1 = seqfeature_1;
    }

    public Term getTerm() {
        return this.term;
    }
    
    public void setTerm(Term term) {
        this.term = term;
    }

    public Integer getDistance() {
        return this.distance;
    }
    
    public void setDistance(Integer distance) {
        this.distance = distance;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SeqfeaturePathId) ) return false;
		 SeqfeaturePathId castOther = ( SeqfeaturePathId ) other; 
         
		 return ( (this.getSeqfeature()==castOther.getSeqfeature()) || ( this.getSeqfeature()!=null && castOther.getSeqfeature()!=null && this.getSeqfeature().equals(castOther.getSeqfeature()) ) )
 && ( (this.getSeqfeature_1()==castOther.getSeqfeature_1()) || ( this.getSeqfeature_1()!=null && castOther.getSeqfeature_1()!=null && this.getSeqfeature_1().equals(castOther.getSeqfeature_1()) ) )
 && ( (this.getTerm()==castOther.getTerm()) || ( this.getTerm()!=null && castOther.getTerm()!=null && this.getTerm().equals(castOther.getTerm()) ) )
 && ( (this.getDistance()==castOther.getDistance()) || ( this.getDistance()!=null && castOther.getDistance()!=null && this.getDistance().equals(castOther.getDistance()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSeqfeature() == null ? 0 : this.getSeqfeature().hashCode() );
         result = 37 * result + ( getSeqfeature_1() == null ? 0 : this.getSeqfeature_1().hashCode() );
         result = 37 * result + ( getTerm() == null ? 0 : this.getTerm().hashCode() );
         result = 37 * result + ( getDistance() == null ? 0 : this.getDistance().hashCode() );
         return result;
   }   





}