package org.nescent.evogen.hibernate;



/**
 * TaxonName generated by MyEclipse - Hibernate Tools
 */

public class TaxonName  implements java.io.Serializable {


    // Fields    

     private TaxonNameId id;
     private Taxon taxon;


    // Constructors

    /** default constructor */
    public TaxonName() {
    }

    
    /** full constructor */
    public TaxonName(Taxon taxon) {
        this.taxon = taxon;
    }

   
    // Property accessors

    public TaxonNameId getId() {
        return this.id;
    }
    
    public void setId(TaxonNameId id) {
        this.id = id;
    }

    public Taxon getTaxon() {
        return this.taxon;
    }
    
    public void setTaxon(Taxon taxon) {
        this.taxon = taxon;
    }
   








}