package org.nescent.evogen.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * Taxon generated by MyEclipse - Hibernate Tools
 */

public class Taxon  implements java.io.Serializable {


    // Fields    

     private Integer taxonId;
     private Integer ncbiTaxonId;
     private Integer parentTaxonId;
     private String nodeRank;
     private Short geneticCode;
     private Short mitoGeneticCode;
     private Integer leftValue;
     private Integer rightValue;
     private Set taxonNames = new HashSet(0);
     private Set bioentries = new HashSet(0);
     private Set nodes = new HashSet(0);


    // Constructors

    /** default constructor */
    public Taxon() {
    }

    
    /** full constructor */
    public Taxon(Integer ncbiTaxonId, Integer parentTaxonId, String nodeRank, Short geneticCode, Short mitoGeneticCode, Integer leftValue, Integer rightValue, Set taxonNames, Set bioentries, Set nodes) {
        this.ncbiTaxonId = ncbiTaxonId;
        this.parentTaxonId = parentTaxonId;
        this.nodeRank = nodeRank;
        this.geneticCode = geneticCode;
        this.mitoGeneticCode = mitoGeneticCode;
        this.leftValue = leftValue;
        this.rightValue = rightValue;
        this.taxonNames = taxonNames;
        this.bioentries = bioentries;
        this.nodes = nodes;
    }

   
    // Property accessors

    public Integer getTaxonId() {
        return this.taxonId;
    }
    
    public void setTaxonId(Integer taxonId) {
        this.taxonId = taxonId;
    }

    public Integer getNcbiTaxonId() {
        return this.ncbiTaxonId;
    }
    
    public void setNcbiTaxonId(Integer ncbiTaxonId) {
        this.ncbiTaxonId = ncbiTaxonId;
    }

    public Integer getParentTaxonId() {
        return this.parentTaxonId;
    }
    
    public void setParentTaxonId(Integer parentTaxonId) {
        this.parentTaxonId = parentTaxonId;
    }

    public String getNodeRank() {
        return this.nodeRank;
    }
    
    public void setNodeRank(String nodeRank) {
        this.nodeRank = nodeRank;
    }

    public Short getGeneticCode() {
        return this.geneticCode;
    }
    
    public void setGeneticCode(Short geneticCode) {
        this.geneticCode = geneticCode;
    }

    public Short getMitoGeneticCode() {
        return this.mitoGeneticCode;
    }
    
    public void setMitoGeneticCode(Short mitoGeneticCode) {
        this.mitoGeneticCode = mitoGeneticCode;
    }

    public Integer getLeftValue() {
        return this.leftValue;
    }
    
    public void setLeftValue(Integer leftValue) {
        this.leftValue = leftValue;
    }

    public Integer getRightValue() {
        return this.rightValue;
    }
    
    public void setRightValue(Integer rightValue) {
        this.rightValue = rightValue;
    }

    public Set getTaxonNames() {
        return this.taxonNames;
    }
    
    public void setTaxonNames(Set taxonNames) {
        this.taxonNames = taxonNames;
    }

    public Set getBioentries() {
        return this.bioentries;
    }
    
    public void setBioentries(Set bioentries) {
        this.bioentries = bioentries;
    }

    public Set getNodes() {
        return this.nodes;
    }
    
    public void setNodes(Set nodes) {
        this.nodes = nodes;
    }
   








}