package org.nescent.evogen.hibernate;



/**
 * TermPath generated by MyEclipse - Hibernate Tools
 */

public class TermPath  implements java.io.Serializable {


    // Fields    

     private Integer termPathId;
     private Term termBySubjectTermId;
     private Term termByObjectTermId;
     private Term termByPredicateTermId;
     private Ontology ontology;
     private Integer distance;


    // Constructors

    /** default constructor */
    public TermPath() {
    }

	/** minimal constructor */
    public TermPath(Term termBySubjectTermId, Term termByObjectTermId, Term termByPredicateTermId, Ontology ontology) {
        this.termBySubjectTermId = termBySubjectTermId;
        this.termByObjectTermId = termByObjectTermId;
        this.termByPredicateTermId = termByPredicateTermId;
        this.ontology = ontology;
    }
    
    /** full constructor */
    public TermPath(Term termBySubjectTermId, Term termByObjectTermId, Term termByPredicateTermId, Ontology ontology, Integer distance) {
        this.termBySubjectTermId = termBySubjectTermId;
        this.termByObjectTermId = termByObjectTermId;
        this.termByPredicateTermId = termByPredicateTermId;
        this.ontology = ontology;
        this.distance = distance;
    }

   
    // Property accessors

    public Integer getTermPathId() {
        return this.termPathId;
    }
    
    public void setTermPathId(Integer termPathId) {
        this.termPathId = termPathId;
    }

    public Term getTermBySubjectTermId() {
        return this.termBySubjectTermId;
    }
    
    public void setTermBySubjectTermId(Term termBySubjectTermId) {
        this.termBySubjectTermId = termBySubjectTermId;
    }

    public Term getTermByObjectTermId() {
        return this.termByObjectTermId;
    }
    
    public void setTermByObjectTermId(Term termByObjectTermId) {
        this.termByObjectTermId = termByObjectTermId;
    }

    public Term getTermByPredicateTermId() {
        return this.termByPredicateTermId;
    }
    
    public void setTermByPredicateTermId(Term termByPredicateTermId) {
        this.termByPredicateTermId = termByPredicateTermId;
    }

    public Ontology getOntology() {
        return this.ontology;
    }
    
    public void setOntology(Ontology ontology) {
        this.ontology = ontology;
    }

    public Integer getDistance() {
        return this.distance;
    }
    
    public void setDistance(Integer distance) {
        this.distance = distance;
    }
   








}