package org.nescent.evogen.hibernate;



/**
 * TermRelationshipTerm generated by MyEclipse - Hibernate Tools
 */

public class TermRelationshipTerm  implements java.io.Serializable {


    // Fields    

     private Integer termRelationshipId;
     private Term term;
     private TermRelationship termRelationship;


    // Constructors

    /** default constructor */
    public TermRelationshipTerm() {
    }

    
    /** full constructor */
    public TermRelationshipTerm(Term term, TermRelationship termRelationship) {
        this.term = term;
        this.termRelationship = termRelationship;
    }

   
    // Property accessors

    public Integer getTermRelationshipId() {
        return this.termRelationshipId;
    }
    
    public void setTermRelationshipId(Integer termRelationshipId) {
        this.termRelationshipId = termRelationshipId;
    }

    public Term getTerm() {
        return this.term;
    }
    
    public void setTerm(Term term) {
        this.term = term;
    }

    public TermRelationship getTermRelationship() {
        return this.termRelationship;
    }
    
    public void setTermRelationship(TermRelationship termRelationship) {
        this.termRelationship = termRelationship;
    }
   








}