package org.nescent.evogen.hibernate;



/**
 * TermSynonym generated by MyEclipse - Hibernate Tools
 */

public class TermSynonym  implements java.io.Serializable {


    // Fields    

     private TermSynonymId id;


    // Constructors

    /** default constructor */
    public TermSynonym() {
    }

    

   
    // Property accessors

    public TermSynonymId getId() {
        return this.id;
    }
    
    public void setId(TermSynonymId id) {
        this.id = id;
    }
   








}