package org.nescent.evogen.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * Term generated by MyEclipse - Hibernate Tools
 */

public class Term  implements java.io.Serializable {


    // Fields    

     private Integer termId;
     private Ontology ontology;
     private String name;
     private String definition;
     private String identifier;
     private String isObsolete;
     private Set termRelationshipsForObjectTermId = new HashSet(0);
     private Set bioentryQualifierValues = new HashSet(0);
     private Set termSynonyms = new HashSet(0);
     private Set nodeAttributeValues = new HashSet(0);
     private Set termRelationshipTerms = new HashSet(0);
     private Set termPathsForSubjectTermId = new HashSet(0);
     private Set locationQualifierValues = new HashSet(0);
     private Set edgeAttributeValues = new HashSet(0);
     private Set bioentryRelationships = new HashSet(0);
     private Set seqfeaturesForTypeTermId = new HashSet(0);
     private Set dbxrefQualifierValues = new HashSet(0);
     private Set seqfeaturePaths = new HashSet(0);
     private Set termPathsForObjectTermId = new HashSet(0);
     private Set termDbxrefs = new HashSet(0);
     private Set seqfeatureQualifierValues = new HashSet(0);
     private Set termPathsForPredicateTermId = new HashSet(0);
     private Set seqfeatureRelationships = new HashSet(0);
     private Set seqfeaturesForSourceTermId = new HashSet(0);
     private Set termRelationshipsForSubjectTermId = new HashSet(0);
     private Set termRelationshipsForPredicateTermId = new HashSet(0);
     private Set locations = new HashSet(0);
     private Set bioentryPaths = new HashSet(0);


    // Constructors

    /** default constructor */
    public Term() {
    }

	/** minimal constructor */
    public Term(Ontology ontology, String name) {
        this.ontology = ontology;
        this.name = name;
    }
    
    /** full constructor */
    public Term(Ontology ontology, String name, String definition, String identifier, String isObsolete, Set termRelationshipsForObjectTermId, Set bioentryQualifierValues, Set termSynonyms, Set nodeAttributeValues, Set termRelationshipTerms, Set termPathsForSubjectTermId, Set locationQualifierValues, Set edgeAttributeValues, Set bioentryRelationships, Set seqfeaturesForTypeTermId, Set dbxrefQualifierValues, Set seqfeaturePaths, Set termPathsForObjectTermId, Set termDbxrefs, Set seqfeatureQualifierValues, Set termPathsForPredicateTermId, Set seqfeatureRelationships, Set seqfeaturesForSourceTermId, Set termRelationshipsForSubjectTermId, Set termRelationshipsForPredicateTermId, Set locations, Set bioentryPaths) {
        this.ontology = ontology;
        this.name = name;
        this.definition = definition;
        this.identifier = identifier;
        this.isObsolete = isObsolete;
        this.termRelationshipsForObjectTermId = termRelationshipsForObjectTermId;
        this.bioentryQualifierValues = bioentryQualifierValues;
        this.termSynonyms = termSynonyms;
        this.nodeAttributeValues = nodeAttributeValues;
        this.termRelationshipTerms = termRelationshipTerms;
        this.termPathsForSubjectTermId = termPathsForSubjectTermId;
        this.locationQualifierValues = locationQualifierValues;
        this.edgeAttributeValues = edgeAttributeValues;
        this.bioentryRelationships = bioentryRelationships;
        this.seqfeaturesForTypeTermId = seqfeaturesForTypeTermId;
        this.dbxrefQualifierValues = dbxrefQualifierValues;
        this.seqfeaturePaths = seqfeaturePaths;
        this.termPathsForObjectTermId = termPathsForObjectTermId;
        this.termDbxrefs = termDbxrefs;
        this.seqfeatureQualifierValues = seqfeatureQualifierValues;
        this.termPathsForPredicateTermId = termPathsForPredicateTermId;
        this.seqfeatureRelationships = seqfeatureRelationships;
        this.seqfeaturesForSourceTermId = seqfeaturesForSourceTermId;
        this.termRelationshipsForSubjectTermId = termRelationshipsForSubjectTermId;
        this.termRelationshipsForPredicateTermId = termRelationshipsForPredicateTermId;
        this.locations = locations;
        this.bioentryPaths = bioentryPaths;
    }

   
    // Property accessors

    public Integer getTermId() {
        return this.termId;
    }
    
    public void setTermId(Integer termId) {
        this.termId = termId;
    }

    public Ontology getOntology() {
        return this.ontology;
    }
    
    public void setOntology(Ontology ontology) {
        this.ontology = ontology;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getDefinition() {
        return this.definition;
    }
    
    public void setDefinition(String definition) {
        this.definition = definition;
    }

    public String getIdentifier() {
        return this.identifier;
    }
    
    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    public String getIsObsolete() {
        return this.isObsolete;
    }
    
    public void setIsObsolete(String isObsolete) {
        this.isObsolete = isObsolete;
    }

    public Set getTermRelationshipsForObjectTermId() {
        return this.termRelationshipsForObjectTermId;
    }
    
    public void setTermRelationshipsForObjectTermId(Set termRelationshipsForObjectTermId) {
        this.termRelationshipsForObjectTermId = termRelationshipsForObjectTermId;
    }

    public Set getBioentryQualifierValues() {
        return this.bioentryQualifierValues;
    }
    
    public void setBioentryQualifierValues(Set bioentryQualifierValues) {
        this.bioentryQualifierValues = bioentryQualifierValues;
    }

    public Set getTermSynonyms() {
        return this.termSynonyms;
    }
    
    public void setTermSynonyms(Set termSynonyms) {
        this.termSynonyms = termSynonyms;
    }

    public Set getNodeAttributeValues() {
        return this.nodeAttributeValues;
    }
    
    public void setNodeAttributeValues(Set nodeAttributeValues) {
        this.nodeAttributeValues = nodeAttributeValues;
    }

    public Set getTermRelationshipTerms() {
        return this.termRelationshipTerms;
    }
    
    public void setTermRelationshipTerms(Set termRelationshipTerms) {
        this.termRelationshipTerms = termRelationshipTerms;
    }

    public Set getTermPathsForSubjectTermId() {
        return this.termPathsForSubjectTermId;
    }
    
    public void setTermPathsForSubjectTermId(Set termPathsForSubjectTermId) {
        this.termPathsForSubjectTermId = termPathsForSubjectTermId;
    }

    public Set getLocationQualifierValues() {
        return this.locationQualifierValues;
    }
    
    public void setLocationQualifierValues(Set locationQualifierValues) {
        this.locationQualifierValues = locationQualifierValues;
    }

    public Set getEdgeAttributeValues() {
        return this.edgeAttributeValues;
    }
    
    public void setEdgeAttributeValues(Set edgeAttributeValues) {
        this.edgeAttributeValues = edgeAttributeValues;
    }

    public Set getBioentryRelationships() {
        return this.bioentryRelationships;
    }
    
    public void setBioentryRelationships(Set bioentryRelationships) {
        this.bioentryRelationships = bioentryRelationships;
    }

    public Set getSeqfeaturesForTypeTermId() {
        return this.seqfeaturesForTypeTermId;
    }
    
    public void setSeqfeaturesForTypeTermId(Set seqfeaturesForTypeTermId) {
        this.seqfeaturesForTypeTermId = seqfeaturesForTypeTermId;
    }

    public Set getDbxrefQualifierValues() {
        return this.dbxrefQualifierValues;
    }
    
    public void setDbxrefQualifierValues(Set dbxrefQualifierValues) {
        this.dbxrefQualifierValues = dbxrefQualifierValues;
    }

    public Set getSeqfeaturePaths() {
        return this.seqfeaturePaths;
    }
    
    public void setSeqfeaturePaths(Set seqfeaturePaths) {
        this.seqfeaturePaths = seqfeaturePaths;
    }

    public Set getTermPathsForObjectTermId() {
        return this.termPathsForObjectTermId;
    }
    
    public void setTermPathsForObjectTermId(Set termPathsForObjectTermId) {
        this.termPathsForObjectTermId = termPathsForObjectTermId;
    }

    public Set getTermDbxrefs() {
        return this.termDbxrefs;
    }
    
    public void setTermDbxrefs(Set termDbxrefs) {
        this.termDbxrefs = termDbxrefs;
    }

    public Set getSeqfeatureQualifierValues() {
        return this.seqfeatureQualifierValues;
    }
    
    public void setSeqfeatureQualifierValues(Set seqfeatureQualifierValues) {
        this.seqfeatureQualifierValues = seqfeatureQualifierValues;
    }

    public Set getTermPathsForPredicateTermId() {
        return this.termPathsForPredicateTermId;
    }
    
    public void setTermPathsForPredicateTermId(Set termPathsForPredicateTermId) {
        this.termPathsForPredicateTermId = termPathsForPredicateTermId;
    }

    public Set getSeqfeatureRelationships() {
        return this.seqfeatureRelationships;
    }
    
    public void setSeqfeatureRelationships(Set seqfeatureRelationships) {
        this.seqfeatureRelationships = seqfeatureRelationships;
    }

    public Set getSeqfeaturesForSourceTermId() {
        return this.seqfeaturesForSourceTermId;
    }
    
    public void setSeqfeaturesForSourceTermId(Set seqfeaturesForSourceTermId) {
        this.seqfeaturesForSourceTermId = seqfeaturesForSourceTermId;
    }

    public Set getTermRelationshipsForSubjectTermId() {
        return this.termRelationshipsForSubjectTermId;
    }
    
    public void setTermRelationshipsForSubjectTermId(Set termRelationshipsForSubjectTermId) {
        this.termRelationshipsForSubjectTermId = termRelationshipsForSubjectTermId;
    }

    public Set getTermRelationshipsForPredicateTermId() {
        return this.termRelationshipsForPredicateTermId;
    }
    
    public void setTermRelationshipsForPredicateTermId(Set termRelationshipsForPredicateTermId) {
        this.termRelationshipsForPredicateTermId = termRelationshipsForPredicateTermId;
    }

    public Set getLocations() {
        return this.locations;
    }
    
    public void setLocations(Set locations) {
        this.locations = locations;
    }

    public Set getBioentryPaths() {
        return this.bioentryPaths;
    }
    
    public void setBioentryPaths(Set bioentryPaths) {
        this.bioentryPaths = bioentryPaths;
    }
   








}