package org.nescent.evogen.hibernate;



/**
 * TermDbxrefId generated by MyEclipse - Hibernate Tools
 */

public class TermDbxrefId  implements java.io.Serializable {


    // Fields    

     private Term term;
     private Dbxref dbxref;


    // Constructors

    /** default constructor */
    public TermDbxrefId() {
    }

    
    /** full constructor */
    public TermDbxrefId(Term term, Dbxref dbxref) {
        this.term = term;
        this.dbxref = dbxref;
    }

   
    // Property accessors

    public Term getTerm() {
        return this.term;
    }
    
    public void setTerm(Term term) {
        this.term = term;
    }

    public Dbxref getDbxref() {
        return this.dbxref;
    }
    
    public void setDbxref(Dbxref dbxref) {
        this.dbxref = dbxref;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TermDbxrefId) ) return false;
		 TermDbxrefId castOther = ( TermDbxrefId ) other; 
         
		 return ( (this.getTerm()==castOther.getTerm()) || ( this.getTerm()!=null && castOther.getTerm()!=null && this.getTerm().equals(castOther.getTerm()) ) )
 && ( (this.getDbxref()==castOther.getDbxref()) || ( this.getDbxref()!=null && castOther.getDbxref()!=null && this.getDbxref().equals(castOther.getDbxref()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTerm() == null ? 0 : this.getTerm().hashCode() );
         result = 37 * result + ( getDbxref() == null ? 0 : this.getDbxref().hashCode() );
         return result;
   }   





}