package org.nescent.evogen.hibernate;



/**
 * TermSynonymId generated by MyEclipse - Hibernate Tools
 */

public class TermSynonymId  implements java.io.Serializable {


    // Fields    

     private Term term;
     private String synonym;


    // Constructors

    /** default constructor */
    public TermSynonymId() {
    }

    
    /** full constructor */
    public TermSynonymId(Term term, String synonym) {
        this.term = term;
        this.synonym = synonym;
    }

   
    // Property accessors

    public Term getTerm() {
        return this.term;
    }
    
    public void setTerm(Term term) {
        this.term = term;
    }

    public String getSynonym() {
        return this.synonym;
    }
    
    public void setSynonym(String synonym) {
        this.synonym = synonym;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TermSynonymId) ) return false;
		 TermSynonymId castOther = ( TermSynonymId ) other; 
         
		 return ( (this.getTerm()==castOther.getTerm()) || ( this.getTerm()!=null && castOther.getTerm()!=null && this.getTerm().equals(castOther.getTerm()) ) )
 && ( (this.getSynonym()==castOther.getSynonym()) || ( this.getSynonym()!=null && castOther.getSynonym()!=null && this.getSynonym().equals(castOther.getSynonym()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTerm() == null ? 0 : this.getTerm().hashCode() );
         result = 37 * result + ( getSynonym() == null ? 0 : this.getSynonym().hashCode() );
         return result;
   }   





}