package org.nescent.evogen.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * Tree generated by MyEclipse - Hibernate Tools
 */

public class Tree  implements java.io.Serializable {


    // Fields    

     private Integer treeId;
     private Biodatabase biodatabase;
     private Node node;
     private String name;
     private String identifier;
     private Byte isRooted;
     private Set nodes = new HashSet(0);


    // Constructors

    /** default constructor */
    public Tree() {
    }

	/** minimal constructor */
    public Tree(Biodatabase biodatabase, Node node, String name) {
        this.biodatabase = biodatabase;
        this.node = node;
        this.name = name;
    }
    
    /** full constructor */
    public Tree(Biodatabase biodatabase, Node node, String name, String identifier, Byte isRooted, Set nodes) {
        this.biodatabase = biodatabase;
        this.node = node;
        this.name = name;
        this.identifier = identifier;
        this.isRooted = isRooted;
        this.nodes = nodes;
    }

   
    // Property accessors

    public Integer getTreeId() {
        return this.treeId;
    }
    
    public void setTreeId(Integer treeId) {
        this.treeId = treeId;
    }

    public Biodatabase getBiodatabase() {
        return this.biodatabase;
    }
    
    public void setBiodatabase(Biodatabase biodatabase) {
        this.biodatabase = biodatabase;
    }

    public Node getNode() {
        return this.node;
    }
    
    public void setNode(Node node) {
        this.node = node;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getIdentifier() {
        return this.identifier;
    }
    
    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    public Byte getIsRooted() {
        return this.isRooted;
    }
    
    public void setIsRooted(Byte isRooted) {
        this.isRooted = isRooted;
    }

    public Set getNodes() {
        return this.nodes;
    }
    
    public void setNodes(Set nodes) {
        this.nodes = nodes;
    }
   








}